import {
  users,
  haras,
  proprietarios,
  cavalos,
  baias,
  coberturas,
  consignacoes,
  leiloes,
  lotes,
  transacoes,
  alertas,
} from "./schema";

const now = new Date();

export const mockUsers = [
  {
    id: 1,
    openId: "dev-user-1",
    name: "Administrador",
    email: "admin@harasmaj.com.br",
    loginMethod: "dev",
    role: "admin" as const,
    harasId: 1,
    ativo: true,
    createdAt: now,
    updatedAt: now,
    lastSignedIn: now,
  },
  {
    id: 2,
    openId: "dev-func-1",
    name: "João Funcionário",
    email: "joao@harasmaj.com.br",
    loginMethod: "dev",
    role: "funcionario" as const,
    harasId: 1,
    ativo: true,
    createdAt: now,
    updatedAt: now,
    lastSignedIn: now,
  },
];

export const mockHaras = [
  {
    id: 1,
    nome: "Haras Maj",
    cnpj: "12.345.678/0001-90",
    endereco: "Rodovia BR-153, Km 42 - Uberaba/MG",
    telefone: "(34) 3333-4444",
    email: "contato@harasmaj.com.br",
    website: "www.harasmaj.com.br",
    logo: null,
    descricao: "Haras especializado em Mangalarga Marchador",
    ativo: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockProprietarios = [
  {
    id: 1,
    harasId: 1,
    nome: "Pedro Santos",
    cpfCnpj: "123.456.789-00",
    email: "pedro@email.com",
    telefone: "(34) 99999-1111",
    endereco: "Rua das Flores, 123 - Uberaba/MG",
    cidade: "Uberaba",
    estado: "MG",
    ativo: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    harasId: 1,
    nome: "Maria Oliveira",
    cpfCnpj: "987.654.321-00",
    email: "maria@email.com",
    telefone: "(34) 99999-2222",
    endereco: "Av. Principal, 456 - Uberaba/MG",
    cidade: "Uberaba",
    estado: "MG",
    ativo: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockCavalos = [
  {
    id: 1,
    harasId: 1,
    nome: "Famoso do Haras Maj",
    registroABCCMM: "MM12345",
    raca: "Mangalarga Marchador" as const,
    sexo: "macho" as const,
    dataNascimento: new Date("2018-03-15"),
    cor: "Castanho",
    microchip: "123456789012345",
    status: "ativo" as const,
    proprietarioId: null,
    genealogia: { pai: "ABC", mae: "XYZ" },
    historicoMedico: null,
    fotos: [],
    documentos: [],
    observacoes: "Cavalo de elite",
    dataRegistro: now,
    updatedAt: now,
  },
  {
    id: 2,
    harasId: 1,
    nome: "Esperança do Porto",
    registroABCCMM: "MM12346",
    raca: "Mangalarga Marchador" as const,
    sexo: "fêmea" as const,
    dataNascimento: new Date("2020-05-20"),
    cor: "Alazã",
    microchip: "123456789012346",
    status: "ativo" as const,
    proprietarioId: 1,
    genealogia: { pai: "DEF", mae: "WXY" },
    historicoMedico: null,
    fotos: [],
    documentos: [],
    observacoes: null,
    dataRegistro: now,
    updatedAt: now,
  },
  {
    id: 3,
    harasId: 1,
    nome: "Diamante Negro",
    registroABCCMM: "MM12347",
    raca: "Mangalarga Marchador" as const,
    sexo: "macho" as const,
    dataNascimento: new Date("2019-08-10"),
    cor: "Preta",
    microchip: "123456789012347",
    status: "consignado" as const,
    proprietarioId: 2,
    genealogia: { pai: "GHI", mae: "ZWA" },
    historicoMedico: null,
    fotos: [],
    documentos: [],
    observacoes: "Consignado para venda",
    dataRegistro: now,
    updatedAt: now,
  },
  {
    id: 4,
    harasId: 1,
    nome: "Luna da Serra",
    registroABCCMM: "MM12348",
    raca: "Mangalarga Marchador" as const,
    sexo: "fêmea" as const,
    dataNascimento: new Date("2021-01-25"),
    cor: "Tordilha",
    microchip: "123456789012348",
    status: "ativo" as const,
    proprietarioId: null,
    genealogia: { pai: "JKL", mae: "VUX" },
    historicoMedico: null,
    fotos: [],
    documentos: [],
    observacoes: null,
    dataRegistro: now,
    updatedAt: now,
  },
  {
    id: 5,
    harasId: 1,
    nome: "Vencedor Imperial",
    registroABCCMM: "QM98765",
    raca: "Quarto de Milha" as const,
    sexo: "macho" as const,
    dataNascimento: new Date("2017-11-30"),
    cor: "Baio",
    microchip: "123456789012349",
    status: "ativo" as const,
    proprietarioId: null,
    genealogia: { pai: "AAA", mae: "BBB" },
    historicoMedico: null,
    fotos: [],
    documentos: [],
    observacoes: "Cavalo de corrida",
    dataRegistro: now,
    updatedAt: now,
  },
];

export const mockBaias = [
  {
    id: 1,
    harasId: 1,
    numero: "A01",
    tipo: "individual" as const,
    status: "ocupada" as const,
    cavaloId: 1,
    dataOcupacao: new Date("2024-01-15"),
    dataLiberacao: null,
    valorAluguel: "1500.00",
    ultimoAluguel: null,
    condicoes: { limpeza: "boa", alimentacao: "3x/dia" },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    harasId: 1,
    numero: "A02",
    tipo: "individual" as const,
    status: "ocupada" as const,
    cavaloId: 2,
    dataOcupacao: new Date("2024-02-01"),
    dataLiberacao: null,
    valorAluguel: "1500.00",
    ultimoAluguel: null,
    condicoes: { limpeza: "boa", alimentacao: "3x/dia" },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 3,
    harasId: 1,
    numero: "A03",
    tipo: "individual" as const,
    status: "disponivel" as const,
    cavaloId: null,
    dataOcupacao: null,
    dataLiberacao: null,
    valorAluguel: "1500.00",
    ultimoAluguel: null,
    condicoes: { limpeza: "boa" },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 4,
    harasId: 1,
    numero: "B01",
    tipo: "coletiva" as const,
    status: "disponivel" as const,
    cavaloId: null,
    dataOcupacao: null,
    dataLiberacao: null,
    valorAluguel: "2500.00",
    ultimoAluguel: null,
    condicoes: { limpeza: "boa", capacidade: 4 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 5,
    harasId: 1,
    numero: "M01",
    tipo: "maternidade" as const,
    status: "disponivel" as const,
    cavaloId: null,
    dataOcupacao: null,
    dataLiberacao: null,
    valorAluguel: "2000.00",
    ultimoAluguel: null,
    condicoes: { limpeza: "excelente" },
    createdAt: now,
    updatedAt: now,
  },
];

export const mockCoberturas = [
  {
    id: 1,
    harasId: 1,
    tipo: "inseminacao_artificial" as const,
    egeaId: 1,
    cavaloId: 1,
    dataAgendamento: new Date("2024-06-15"),
    dataRealizacao: null,
    status: "agendada" as const,
    resultado: null,
    custoServico: "500.00",
    observacoes: "Primeira tentativa",
    dataVencimento: new Date("2024-07-15"),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    harasId: 1,
    tipo: "cobracao_natural" as const,
    egeaId: 2,
    cavaloId: 4,
    dataAgendamento: new Date("2024-05-20"),
    dataRealizacao: new Date("2024-05-20"),
    status: "sucesso" as const,
    resultado: { confirmacao: true, dataPrevista: "2025-02-20" },
    custoServico: "800.00",
    observacoes: "Cobertura realizada com sucesso",
    dataVencimento: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockConsignacoes = [
  {
    id: 1,
    harasId: 1,
    cavaloId: 3,
    proprietarioId: 2,
    dataInicio: new Date("2024-01-01"),
    dataFim: new Date("2024-12-31"),
    comissaoPercentual: "15.00",
    statusVenda: "disponivel" as const,
    dataPagamento: null,
    valorVenda: "0",
    comissaoPaga: false,
    contrato: null,
    observacoes: "Consignação para leilões",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockLeiloes = [
  {
    id: 1,
    harasId: 1,
    nome: "Leilão de Verão 2024",
    dataEvento: new Date("2024-12-15"),
    status: "planejado" as const,
    totalLotes: 0,
    totalArrecadado: "0",
    descricao: "Leilão de cavalos Mangalarga Marchador",
    regulamento: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    harasId: 1,
    nome: "Leilão de Primavera 2024",
    dataEvento: new Date("2024-09-20"),
    status: "encerrado" as const,
    totalLotes: 5,
    totalArrecadado: "250000.00",
    descricao: "Leilão de Elite",
    regulamento: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockLotes = [
  {
    id: 1,
    leilaoId: 2,
    numero: 1,
    cavaloId: 1,
    lanceInicial: "50000.00",
    lanceFinal: "65000.00",
    status: "vendido" as const,
    comprador: "Carlos Silva",
    dataVenda: new Date("2024-09-20"),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    leilaoId: 2,
    numero: 2,
    cavaloId: 5,
    lanceInicial: "80000.00",
    lanceFinal: "95000.00",
    status: "vendido" as const,
    compra: "Ana Pereira",
    dataVenda: new Date("2024-09-20"),
    createdAt: now,
    updatedAt: now,
  },
];

export const mockTransacoes = [
  {
    id: 1,
    harasId: 1,
    tipo: "venda" as const,
    referencia: "Lote 1 - Leilao Primavera",
    referenciaTabela: "lotes",
    valor: "65000.00",
    dataTransacao: new Date("2024-09-20"),
    status: "confirmada" as const,
    descricao: "Venda do cavalo Famoso do Haras Maj",
    usuarioId: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    harasId: 1,
    tipo: "aluguel" as const,
    referencia: "Baia A01",
    referenciaTabela: "baias",
    valor: "1500.00",
    dataTransacao: new Date("2024-06-01"),
    status: "confirmada" as const,
    descricao: "Aluguel baia mês 06/2024",
    usuarioId: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 3,
    harasId: 1,
    tipo: "despesa" as const,
    referencia: "Nota Fiscal 123",
    referenciaTabela: null,
    valor: "350.00",
    dataTransacao: new Date("2024-06-10"),
    status: "confirmada" as const,
    descricao: "Ração para cavalos",
    usuarioId: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 4,
    harasId: 1,
    tipo: "comissao" as const,
    referencia: "Consignação ID 1",
    referenciaTabela: "consignacoes",
    valor: "1500.00",
    dataTransacao: new Date("2024-06-15"),
    status: "pendente" as const,
    descricao: "Comissão sobre venda consignada",
    usuarioId: 1,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockAlertas = [
  {
    id: 1,
    harasId: 1,
    tipo: "vencimento_aluguel" as const,
    usuarioId: 1,
    titulo: "Aluguel de baia vence em 5 dias",
    mensagem: "O aluguel da baia A01 vence em 5 dias",
    referencia: "Baia A01",
    referenciaTabela: "baias",
    lido: false,
    dataEnvio: now,
    createdAt: now,
  },
  {
    id: 2,
    harasId: 1,
    tipo: "data_leilao" as const,
    usuarioId: 1,
    titulo: "Leilão de Verão se aproxima",
    mensagem: "Faltam 30 dias para o Leilão de Verão 2024",
    referencia: "Leilão 1",
    referenciaTabela: "leiloes",
    lido: false,
    dataEnvio: now,
    createdAt: now,
  },
];

export const mockDb = {
  users: mockUsers,
  haras: mockHaras,
  proprietarios: mockProprietarios,
  cavalos: mockCavalos,
  baias: mockBaias,
  coberturas: mockCoberturas,
  consignacoes: mockConsignacoes,
  leiloes: mockLeiloes,
  lotes: mockLotes,
  transacoes: mockTransacoes,
  alertas: mockAlertas,
};
